insert into user_details(id,birth_date,name) values(1, current_date(), 'Edgar')
insert into user_details(id,birth_date,name) values(2, current_date(), 'Maria')
insert into user_details(id,birth_date,name) values(3, current_date(), 'Luis')
insert into post(id,description,user_id) values (101, 'I want to learn Spring Boot', 1)
insert into post(id,description,user_id) values (102, 'I want to learn MySql', 2)
insert into post(id,description,user_id) values (103, 'I want to learn Angular/Java(SpringBoot)', 3)